In [1]:
# importing numpy
import numpy as np

In [2]:
s = np.array(5)

In [3]:
s.shape

()

In [4]:
x = s + 3

In [6]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Tensors
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [9]:
t.shape

(3, 3, 2, 1)

In [14]:
# changing the shape of a vector

v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [16]:
x = v.reshape(1,4)
x

array([[1, 2, 3, 4]])

In [17]:
x = v.reshape(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [18]:
x = v[None, :]
x

array([[1, 2, 3, 4]])

In [19]:
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

### Element-wise operations

In [20]:
# Adding values without numpy 
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
values

[6, 7, 8, 9, 10]

In [21]:
# The NumPy way
values = [1,2,3,4,5]
values = np.array(values) + 3
values

array([4, 5, 6, 7, 8])

In [22]:
x = np.multiply(values, 2)
x

array([ 8, 10, 12, 14, 16])

In [23]:
x = np.array(values) * 2
x

array([ 8, 10, 12, 14, 16])

In [27]:
# Adding multi-dimensional arrays
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [28]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [29]:
c = a + b
c

array([[ 3,  7],
       [11, 15]])

In [30]:
# Adding incompatible shapes
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a.shape
# displays the following result:
#  (2, 2)

c.shape
# displays the following result:
#  (3, 3)

a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

### NumPy Matrix Multiplication

In [33]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [35]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [37]:
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

**Matrix Product**

In [38]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
a.shape

(2, 4)

In [40]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
b.shape

(4, 3)

In [42]:
c = np.matmul(a,b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [43]:
c.shape

(2, 3)

In [44]:
a = np.array([[1,2],[3,4]])
a
# displays the following result:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # you can call `dot` directly on the `ndarray`
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

array([[ 7, 10],
       [15, 22]])

### Transpose

In [45]:
m = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
# Transpose of m
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [48]:
m_t = m.T
m_t[3][2] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4,   8, 200]])

In [49]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11, 200]])

In [50]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [51]:
inputs.shape

(1, 4)

In [53]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [54]:
weights.shape

(3, 4)

In [56]:
# finding the matrix product
np.matmul(inputs, weights)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [57]:
# finding the matrix product using transpose
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

## Numpy Excersices

In [58]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = input_array / np.max(inputs_minus_min)

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)
    else:
        return np.matmul(m2, m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[-0.125  0.25   0.875]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
